# -*- coding: utf-8 -*-
"""Text_To_Voice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4BipsH_ZlCyjBJnmbSD_w7_04tjXxWn
"""

!pip install gtts

# Language	Code
# English	'en'
# Hindi	'hi'
# French	'fr'
# Spanish	'es'
# Bengali	'bn'

from gtts import gTTS

text = input(str( """Enter your text : """))
tts = gTTS(text=text, lang='en')
tts.save("demo_audio.mp3")

print("Audio file saved as demo_audio.mp3")

from IPython.display import Audio

Audio("demo_audio.mp3")

